### ISSUE TITLE
Firefox version?

### ISSUE THREAD

**Issue by yoasif** [pietervanheijningen/clickbait-remover-for-youtube#1]
It'd be nice to support Firefox, and since the extensions are pretty similar, it might not be too hard: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension

Thanks!

**Comment by p4t4t4** [comment]
I uploaded the .crx file to mozilla and made a working firefox version. [download](https://send.firefox.com/download/3b81555621a2e1d4/#Qh7ZTZGSbwC8vWpuizCuuw)

**Comment by pietervanheijningen** [comment]
I've made a firefox version and submitted it to addons.mozilla.org, just have to wait for it to get reviewed now.

I did have to switch the activeTab permission back to tabs for the firefox manifest as the live switcher did not work with activeTab on firefox. @p4t4t4 's version did work as it was the old 0.1.2 version (i assume)

**Comment by unixfox** [comment]
Is it the extension now available on the Mozilla addons store?

**Comment by pietervanheijningen** [comment]
> Is it the extension now available on the Mozilla addons store?


Soon, still in the review process currently:
![image](https://user-images.githubusercontent.com/28759591/62530083-2fbf6180-b840-11e9-81a3-5fce87da8736.png)
I'll post a link here as soon as its available

**Comment by p4t4t4** [comment]
Want to temporarily put the .xpi file on here (upload it to Google drive or Firefox send or something)?

**Comment by pietervanheijningen** [comment]
I'd rather keep as much people as possible on the latest version and updated through the stores, as I keep finding more and more bugs (just a few minutes ago I pushed a fix for another bug)

If you really want it now you can clone this repository and replace the manifest.json with firefox_manifest.json and make an .xpi file from that.

**Comment by pietervanheijningen** [comment]
Firefox version is live!

https://addons.mozilla.org/en-US/firefox/addon/clickbait-remover-for-youtube/
