### ISSUE TITLE
Whitelist support (to disable addon on non-clickbait channels)

### ISSUE THREAD

**Issue by uselessgithub** [pietervanheijningen/clickbait-remover-for-youtube#11]
Some channels already use non-clickbait thumbnails and select thumbs that represent content correctly. It would be nice to be able to whitelist them so that this addons doesn't change their handpicked thumbnails.

**Comment by pietervanheijningen** [comment]
Would be great, but I haven't found a way to do that with the current method im using (redirects)

Currently the extension has no way of knowing what channels the thumbnails belong to.

**Comment by uselessgithub** [comment]
As a first step, if you can access the tab url with the current permissions, you could whitelist strings and check against https://www.youtube.com/user/xxxxxxxxxxxxx/videos and https://www.youtube.com/channel/xxxxxxxxxxxxxxxxxxxxxxxxx/videos . It would only work on channels though, not on any other youtube page and related content thumbnails. (But better than nothing I think)

**Comment by pietervanheijningen** [comment]
I am currently working on a feature kind of like that, where you can choose on what pages the extension modifies videos. That way you can leave your subscriptions feed unmodified

**Comment by pietervanheijningen** [comment]
> I am currently working on a feature kind of like that, where you can choose on what pages the extension modifies videos. That way you can leave your subscriptions feed unmodified

Turns out that is way more difficult to do as I initially thought, as youtube caches thumbnails across pages, causing everything to be inconsistent. 

Doing it for only for individual seems to be doable, that is, if there is a way to very quickly convert video id's to channel id's. Which might need to involve running a server to do it

**Comment by pietervanheijningen** [comment]
I tried, and failed: https://github.com/pietervanheijningen/clickbait-remover-for-youtube/pull/15

If anyone finds a good way to do it that doesn't impact performance much, feel free to open a PR
