### ISSUE TITLE
Video title option to respect grammar, i.e. capitalise new sentences and the letter "I"

### ISSUE THREAD

**Issue by nocalla** [pietervanheijningen/clickbait-remover-for-youtube#2]
The "capitalise first letter option" should also capitalise the first letter of new sentences, the word "I", and proper nouns. The last one is a lot more involved, but the first two should be reasonably trivial.

**Comment by pietervanheijningen** [comment]
Would be pretty nice, but all 3 of those are going to require running some javascript on the titles. Currently titles are just updated with CSS using the [text-transform property](https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform) which automatically takes care of dynamically loading content, doing the same with javascript would be pretty hard without some resource intensive interval timer.

**Comment by nocalla** [comment]
Ah okay. Last thing I want is to slow things down!

**Comment by wefalltomorrow** [comment]
Would an alternative JS version be able to made like this?

**Comment by pietervanheijningen** [comment]
> Would an alternative JS version be able to made like this?

Not entirely sure what you mean with an alternative JS version, Javascript dialects like typescript and coffeescript just compile down to regular javascript in the end. 

But if you can figure out a way to do this effectively without too much of a performance impact i'd be happy to implement it
