### ISSUE TITLE
Live refresh of changed settings not working within the video player

### ISSUE THREAD

**Issue by mirror176** [pietervanheijningen/clickbait-remover-for-youtube#3]
At the end of a video it populates with more videos to choose from. Changing settings for where to grab the thunbnail from does not work within the player's listed videos but does work on the choices to the right of it.

**Comment by pietervanheijningen** [comment]
Yeah noticed it too, they seem to use background-image instead of a normal image. I'll see when I can fix it

**Comment by pietervanheijningen** [comment]
Fixed it in v0.1.8! Thanks for finding it!
