### ISSUE TITLE
Playlists shown within the video player do not get a new thumbnail

### ISSUE THREAD

**Issue by mirror176** [pietervanheijningen/clickbait-remover-for-youtube#4]
Playlists do not get a new thumbnail even when the playlist on the right of the video player did.

**Comment by pietervanheijningen** [comment]
Do you have an example of a video with this issue? What do you mean with "Playlists shown within the video player" those could be in two places, either at the end of the video as an end card or in the top right slide out info menu. 

End cards are broken either way now, for some reason youtube uses a completely different image loader for those

**Comment by mirror176** [comment]
https://www.youtube.com/watch?v=-D0WnU8-wZA did it for me. It appeared in the list of videos at the end for me and when clicking the 'i' in the top right (first I've done that).
  Their videos have a thumbnail which makes it clear who it is from and what it is about generally which is why I'm thinking about keeping the addon but disabled until content creators make me more angry. Tough call though as I know youtube has already had offtopic recommendations for me that are pure clickbait thumbnails and/or titles. so I've been doing testruns on. Can those two be separated so it would only apply to the ones that get 'recommended for you' instead fo a viewcount as listed on the right?

**Comment by pietervanheijningen** [comment]
Fixed it in v0.1.8! Thanks for finding it!
