### ISSUE TITLE
Don't star this repo

### ISSUE THREAD

**Issue by comfy332** [pietervanheijningen/clickbait-remover-for-youtube#42]
I noticed that installing the extension on Firefox added this repository to my starred repos, would it be possible to remove this "feature"?
Thanks

**Comment by pietervanheijningen** [comment]
This is not the case, and wouldn't even be possible with the permissions that the extension has. Maybe you starred this repo by accident?

**Comment by comfy332** [comment]
It's very possible, I apologise
