### ISSUE TITLE
Initial picture before hitting play is not altered

### ISSUE THREAD

**Issue by mirror176** [pietervanheijningen/clickbait-remover-for-youtube#5]
Not sure if intentional, but having youtube not set to autoplay in firefox leads to it showing the 'thumbnail' as the picture within the video player. Videos I look at usually have a thumbnail that is more like a good book/movie color with a title and related graphic to the actual content and unless clicking a blind link from an outside  email or other webpage then the user likely already had a filtered thumbnail before seeing this.

**Comment by pietervanheijningen** [comment]
Not sure how other people feel about it.
But I do feel like seeing the video thumbnail is sometimes essential to the video. So it might be useful to see it when autoplay is off. It's not really clickbait if you've already clicked on the video.

**Comment by mirror176** [comment]
Overall I think i've seen good come from thumbnails instead of rare clickbait. Wondering if this would be a relevant report to how embedded videos appear on other sites too but pages I know of there bring in a select video based on content around it like a blogpost, news article, etc. Wouldn't revisit unless someone shows a page where a need arises.
