### ISSUE TITLE
Wide permissions request in Chrome

### ISSUE THREAD

**Issue by jeromebaum** [pietervanheijningen/clickbait-remover-for-youtube#53]
I got the following notification in my Chrome:

> Clickbait Remover for Youtube is disabled
>
> To re-enable it, accept the new permissions:
>
> * Block content on any page

Do you know what's happening here?

I checked `manifest.json` in the `master` branch and don't see a reason why this would be happening. That said I am not too familiar with extension development. Seems like it might be related to manifest v3.

**Comment by pietervanheijningen** [comment]
Hey,

Kind of messed up on my part. I had to re-write most of the extension to support the new manifest v3 before the end of the year.
With that Google changed how the permissions work, mainly for intercepting and redirecting network requests.

I didn’t really pay the closest attention to the new permissions, so I gave the extension more than I should have. Namely ``declarativeNetRequest`` was not needed.
I’ve now corrected the mistake and published a new version (0.7.1) with that permission removed. The extension seems to work fine without it.
