### ISSUE TITLE
Icon missing in Firefox

### ISSUE THREAD

**Issue by tfvlrue** [pietervanheijningen/clickbait-remover-for-youtube#57]
Hi,
I'm trying this out in Firefox 115 (on Windows 10) and it seems like there is no way to access the settings. There isn't any "Options" in the extension's drop-down:

![addon_settings](https://github.com/pietervanheijningen/clickbait-remover-for-youtube/assets/35318734/7e3a0e04-71ec-4679-8d36-71050834cf9f)

I noticed the description says "All functionality of the extension is customizable by clicking the extension icon on the top right", but there is no icon visible. The toolbar customization view doesn't have one either:

![toolbar_settings](https://github.com/pietervanheijningen/clickbait-remover-for-youtube/assets/35318734/c6bec9e5-93c0-4608-89e6-e9639fd5ec6f)

I didn't notice anything added to the context menu either. So either I'm really confused or maybe there's a bug here :)

Thanks,
Luke

**Comment by pietervanheijningen** [comment]
https://github.com/pietervanheijningen/clickbait-remover-for-youtube/assets/28759591/36d6860b-432e-40d2-b565-341e6d98b985

Works for me just fine like this on firefox 115, don't see how it could be different on windows (i'm running macOS)

**Comment by tfvlrue** [comment]
Ohh, I see. I had that puzzle piece icon turned off. With it back on, it shows up in that list and I can access the options just fine. The other extensions either auto-pinned their icons to the toolbar, or had their options accessible in the extensions list:

![options](https://github.com/pietervanheijningen/clickbait-remover-for-youtube/assets/35318734/982dade9-e74f-488e-b897-e6e520696449)

Anyway I guess this was a "me" problem :) But it would be nice to have the options for this extension exposed the way others do.

**Comment by sKopheK** [comment]
> Screen.Recording.2023-07-08.at.21.35.55.mov
> 
> Works for me just fine like this on firefox 115, don't see how it could be different on windows (i'm running macOS)

it's not clicking the cog icon as the description say then :)
