### ISSUE TITLE
Consider userscript

### ISSUE THREAD

**Issue by haarp** [pietervanheijningen/clickbait-remover-for-youtube#6]
Really good idea for an addon, thank you for making this!

Would you consider making it an userscript? This will work with any browser that offers an userscript engine or through addons like Greasemonkey/Tampermonkey/Violentmonkey/etc. and won't need a specific browser. And since addons have a tendency to getting disappeared at a whim from addon stores, an userscript would also help resist that.

**Comment by pietervanheijningen** [comment]
Think this extension is a bit too complex to be a userscript.  Don't think they allow the ability to listen for new requests for thumbnails and redirect them accordingly like this extension does.

You could also always clone this repository and install it as a debug extension if it gets taken down from your browser store.

**Comment by gil** [comment]
I gave it a try here just for fun: https://github.com/gil/userscripts/blob/main/youtube-clickbait-reducer.user.js
It won't work as well as the extension. Both thumbnails are loaded, there's often a delay, etc.
But if you need to use it on mobile or some other browser, it may help.
