### ISSUE TITLE
does not work after first page refresh (Brave Browser)

### ISSUE THREAD

**Issue by yaseen-kc** [pietervanheijningen/clickbait-remover-for-youtube#66]

**Comment by Runkel79** [comment]
Got the Same Problem, i hope this will get fixed. I can't stand those stupid clickbait thumbnails.

**Comment by Runkel79** [comment]
Brave got an update today and now Clickbait Remover works for me! Yay! :)

**Comment by yaseen-kc** [comment]
> Brave got an update today and now Clickbait Remover works for me! Yay! :)

yhhh 🔥
