### ISSUE TITLE
Permissions?

### ISSUE THREAD

**Issue by Madis0** [pietervanheijningen/clickbait-remover-for-youtube#7]
Per manifest.json, the permissions are as follows:
```  
"permissions": [
    "*://www.youtube.com/*",
    "*://i.ytimg.com/*",
    "webRequest",
    "storage",
    "webRequestBlocking",
    "activeTab"
  ]
```
The first two make sense, but what are the others used for?

**Comment by pietervanheijningen** [comment]
**webRequest**
This is used to see what thumbnails are being loaded, and handle them accordingly

**webRequestBlocking**
Extra permission besides just webRequest that allows the extension to redirect the thumbnails to the one that you picked

**storage**
Used to locally save your settings in the options menu

**activeTab**
Used to automatically switch thumbnails that are already loaded in a youtube tab to the right one when you switch an option

**Comment by Madis0** [comment]
> **activeTab**
> Used to automatically switch thumbnails that are already loaded in a youtube tab to the right one when you switch an option
Usability-wise it sounds good, but privacy-wise maybe just tell the user to reload the YouTube tabs...

**Comment by pietervanheijningen** [comment]
> Usability-wise it sounds good, but privacy-wise maybe just tell the user to reload the YouTube tabs...

I agree it would be better privacy-wise, but people have been really enjoying the live switcher. It's pretty nice to right away compare what changes options have. Especially as every time you reload some youtube pages you get different videos.

Keep in mind activeTab also respects the website patterns at the top. So it can only access youtube's sites.
