### ISSUE TITLE
Loses settings across restarts when fully clearing history

### ISSUE THREAD

**Issue by mkirisame** [pietervanheijningen/clickbait-remover-for-youtube#9]
Losing settings here because I run a profile sanitizer regularly that scrubs files like the cookie DB and other privacy relevant databases.
Please consider using the correct Storage API to store users' settings across browser sessions:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/get#Examples

The the new one based on the storage directory and old JSON one are around since quite some time:
https://blog.mozilla.org/addons/2018/08/03/new-backend-for-storage-local-api/

When out of 19 addons this is the only one losing settings, I politely beg you to please store things correctly according to Mozilla's developer guidelines.

Your addon has become quite important to me and I want it to be perfect. Willing to give you 5/5 star ratings on Mozilla as soon as this is addressed.

see your proper dir at: ```<profile>\storage\default\```

```<profile>\storage-sync.sqlite``` is **not** the correct place to keep settings

good:
```
const option = await browser.storage.local.get();
browser.storage.local.set();
```

harmful:
```
chrome.storage.sync.get()
chrome.storage.sync.set()
```

Other than that, thank you a lot for great work!

**Comment by pietervanheijningen** [comment]
Right so from what I understand u want me to switch from [storage.sync](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync) to [storage.local](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local) To me the storage.local API is worse, as it doesn't make the settings sync across devices, which I think is a useful feature.

If your profile sanitizer causes these settings to reset I suggest configuring it to not clear addon storage. Both re-launching the browser and re-enabling the extension keeps the settings just fine for me since v0.1.6 on firefox & chrome

**Comment by mkirisame** [comment]
My request does not come from fixed idea, but it is defacto standard with all major extensions (ublock, etc.) I've ever used, and I have discussed this very issue with other developers of addons and they could be reasoned with by my arguments:
https://addons.mozilla.org/de/firefox/addon/remove-cookies-button-ver1x/

For Firefox the standard behaviour of webextensions is to use storage.local, as it is not Chrome. As explained in both links, for performance reasons and security reasons.
With storage.local each sqlite database is isolated from those of other addons und the mentioned directory. (There is a whole other lot of good reasons why to not use storage-sync.)

I can accept a no if it is too difficult for you to implement, but the need to sync the current state of two radio buttons in an option menu across browsers is hardly convincing.
There are addons with databases far larger than 2 key-value entries that also use the correct storage.local API and still manage to allow for sync.

Yes I don't have to sanitize storage-sync, but it made me aware of your addon not using the standard API. You may either ignore my begging and pleas for storage.local or you can consider either calling both browser.storage and chrome.storage for storing the data, or leave your users the choice to select which API they prefer.

Like I said, I can accept a no, but I'd feel better if you could see my point of view and use occams razor:
If I am wrong, why does literally every other major respected developer like gorhill use storage.local?

greetings,
mk

**Comment by mkirisame** [comment]
As this is neither tagged enhancement or feature request and in limbo since a month:
If there is no incentive, please close.
